# Generated by Django 4.2.7 on 2023-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('img_bandera', models.ImageField(upload_to='imagenes/')),
                ('escudo_equipo', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
