# Generated by Django 4.2.7 on 2023-11-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFull', '0002_jugador_nacionalidad_posicionjuego_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionFull.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionFull.posicionjuego'),
        ),
    ]
